title:               Stationers' Paratexts Online
url:                 https://andiesilva.github.io
baseurl:             /spo/

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Andie Silva
  url:               andiesilva.commons.gc.cuny.edu
  email:             

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
